dist: precise

language: php

php:
  - 7.2

addons:
  chrome: stable

install:
  - cp .env.travis .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

before_script:
  - google-chrome-stable --headless --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
  - sleep 10

script:
  - vendor/bin/phpunit
  - php artisan dusk
